### ISSUE TITLE
Feature: Multiple Upload

### ISSUE THREAD

**Issue by FelixMau** [open-modex/oedatamodel_api#33]
## Feature Request

Multiple file uploads via the API can be very helpful, especially when someone wants to upload a large number of CSVs or metadata files. Additionally, this can help with versioning files as it makes it easier to re-upload a newer version.

Currently, uploading a single file at a time can be repetitive and exposes the user to typo mistakes and other human errors.

It would be great to have a fixed folder structure for uploads, such as:

### Datapackage
  * Metadata
    * name_of_table.json
  * Tabledata
    * name_of_table.csv

In this case, the filenames of the data (CSV) and metadata (JSON) should match the table name in the OEP system.

**Comment by henhuy** [comment]
But metadata has to be uploaded just once...
I/you could provide a simple script which uploads multiple datasets automatically...
Otherwise data must be uploaded as zip, which is not recommended. and accessing local file system from API is not possible - so it leaves the user to build a simple script. (we could add script to repo, though!  this is helpful for others)
