### ISSUE TITLE
Genesys Mod Upload - Datapackage is not valid

### ISSUE THREAD

**Issue by LKoeckritz** [open-modex/oedatamodel_api#7]
Thank you Hendrik for getting back to our issue by email. 

I checked again that we are not using any double quotes and removed some other inconsistencies. I zipped the three files with the JSON upload file as attached. I am not receiving an Internal Server Error when uploading this anymore :) (with 'model_draft', 'normalize_output', and ticking both boxes).

[Genesys_mod_2016_original.zip](https://github.com/open-modex/oedatamodel_api/files/6310003/Genesys_mod_2016_original.zip)

However, now it says that the data package is not valid. I will upload the most recent files to nextcloud now as well.

I would be very happy to know what I am doing wrong thank you!

**Comment by henhuy** [comment]
Alright! 
I will have a look tomorrow!

**Comment by henhuy** [comment]
Note: To see all errors you have to open "tasks" tab - there is a list of three items related to your tables (scenario, scalar and timeseries). There you can open tab "errors" to check whats wrong...
I will try to fix some of the errors and track changes.

**Comment by henhuy** [comment]
Scenario:
- one error: region must be json/dict, instead of list (should be `{"DE": ["BB","BE","BW","BY","HB","HE","HH","MV","NI","NW","RP","SH","SL","SN","ST","TH"]}`)

Scalars:
- column "year" is missing (two options: either add column year to data, or remove metadata entry for column "year" from datapackage.json - don't know if upload is valid without year..)
- wrong foreign-key. Foreign-keys have to be consistent in datapackage. (Scenario Id was 1, but foreign-keys in scalars and timeseries had ID 23)

Timeseries:
- date format for "timeindex_start" and "timeindex_stop" is not default (see https://specs.frictionlessdata.io/table-schema/#types-and-formats); you have to adapt datetime format in datapackage.json to `"format": "%d.%m.%Y %H:%M"` in order to make it work
- wrong foreign-key. Foreign-keys have to be consistent in datapackage. (Scenario Id was 1, but foreign-keys in scalars and timeseries had ID 23)

Resulting upload datapackage: 
[Genesys_mod.zip](https://github.com/open-modex/oedatamodel_api/files/6316537/Genesys_mod.zip)

After this changes, upload worked!
ID of your scenario is #17
